// ================================================================
//  js/lang.js  —  i18n via i18next (standard translation library)
//  AWC | Arain World Council
//
//  Drop-in replacement for the old hand-rolled UR/EN dictionaries.
//  Same call signature is preserved: t(key, lang) — so app.js
//  needs ZERO changes beyond this file's import.
//
//  i18next loaded from CDN as an ES module (no build step required).
// ================================================================
import i18next from 'https://cdn.jsdelivr.net/npm/i18next@23.16.8/+esm';

// ── Translation resources ──────────────────────────────────────
// Same flat key→string maps as before, now nested under
// the {lng}.translation shape i18next expects.
const EN = {
siteName:'Arain World Council',
siteTagline:'Unity | Empowerment | Development',
siteSubName:'Bannu Regional Organisation',
heroBadge:'Welcome to AWC',
heroTitle:'Arain World Council',
heroSub:'Empowering Our Next Generation, Proud Of Our Heritage',
heroTagline:'Uniting the Arain Community Worldwide — A Global Platform for Arain Excellence | Strength, Unity, Progress',
heroAboutBtn:'About Us',
heroEventsBtn:'News & Events',
aboutLabel:'Who We Are',
aboutTitle:'Arain World Council (AWC)',
aboutSubtitle:'Serving Communities Through Welfare, Education, and Empowerment',
aboutP1:'Arain World Council - AWC is a non-political, welfare-oriented platform established to unite the global Arain community under one vision of progress, unity, and empowerment.',
aboutP2:'The Council actively works in key areas such as education, employment, youth development, and social welfare.',
aboutP3:'All members contribute voluntarily with dedication and sincerity. The Council believes in transparency, unity, and service to humanity.',
statMembersLabel:'Members',
statProgramsLabel:'Programs',
statCitiesLabel:'Cities',
chairmanBadge:'Global Chairman',
joinBtn:'Join AWC',
programsLabel:'What We Do',
programsTitle:'Programs / Initiatives',
programsDesc:'We work on all the projects below. Our goal is to provide all facilities to the entire Arain community.',
teamLabel:'Our Team',
leadershipTitle:'Meet Our Leadership',
upcomingLabel:'Upcoming',
eventsTitle:'Events & Programs',
touchLabel:'Get In Touch',
contactUs:'Contact Us',
addressLabel:'Address',
hoursLabel:'Opening Hours',
phoneLabel:'Phone',
emailLabel:'Email',
usefulLinks:'Useful Links',
recentNews:'Recent News',
contactUsFooter:'Contact Us',
navHome:'Home',
navAbout:'About Us',
navPrograms:'Programs',
navLeadership:'Leadership',
navEvents:'Events',
navContact:'Contact',
navMembership:'Membership',
navGallery:'Gallery',
heroDept:'Departments',
heroEvents:'Events',
heroGallery:'Gallery',
heroGuide:'Visitors Guide',
membershipTitle:'Apply Membership',
membershipDesc:'From void to light, shaping paths where living moments turn into lasting journeys.',
donateTitle:'Give Donation',
donateDesc:'Do you want to support the Arain Family and make a meaningful difference?',
registerNow:'Register Now',
donateNow:'Donate Now',
seeAllMembers:'See All Members',
moreDetails:'More Details',
formName:'Your Name',
formEmail:'Email Address',
formSubject:'Subject',
formMessage:'Message',
sendMessage:'Send Message',
phName:'Muhammad Ali Arain',
phEmail:'you@example.com',
phSubject:'e.g. Membership Inquiry',
phMessage:'Write your message here…',
galleryTitle:'Gallery',
galleryLabel:'Photo Gallery',
galleryDesc:'Memories from AWC events and milestones.',
galleryEmpty:'No photos yet.',
noEvents:'No events yet.',
noPrograms:'No programs yet.',
noLeaders:'No leaders yet.',
footerDesc:'Arain World Council unites the global Arain community, empowering youth, promoting education, supporting welfare, and building strong networks for progress worldwide.',
footerCopy:'© 2026 Arain World Council (AWC) — All Rights Reserved.',
news1:'AWC Bannu Annual Gathering 2025',
news2:'Youth Leadership Summit Bannu 2025',
pageLabBlog:'Our Blog',
pageLabHistory:'Our History',
pageLabDocs:'Documentation',
pageLabEnv:'Environmental',
pageLabGallery:'Town Gallery',
pageLabDept:'Department',
pageTitleBlog:'AWC Blog',
pageTitleHistory:'AWC History',
pageTitleDocs:'AWC Documentation',
pageTitleEnv:'AWC Environmental Initiatives',
pageTitleGallery:'AWC Town Gallery',
pageTitleDept:'AWC Departments',
pageBodyBlog:'Welcome to the AWC Blog. Stay updated with the latest news, stories, and announcements from the Arain World Council community.',
pageBodyHistory:'The Arain World Council was founded with a vision to unite Arains globally. From humble beginnings, AWC has grown into a worldwide movement for community empowerment and development.',
pageBodyDocs:'Official documents, policies, and guidelines of the Arain World Council. All resources are available for members and the public.',
pageBodyEnv:'AWC is committed to environmental protection and sustainability. We promote tree planting, clean water initiatives, and eco-friendly community programs.',
pageBodyGallery:'Explore photos and memories from AWC events, community gatherings, and milestones across cities and countries.',
pageBodyDept:'AWC operates through multiple departments including Education, Welfare, Youth Affairs, Women Empowerment, and International Relations.',
donateToAWC:'Donate to AWC',
donSub:'Your donation directly supports the Arain community. Transfer to our verified accounts below.',
tabBank:'Bank Transfer',
tabEasypaisa:'Easypaisa',
tabJazzcash:'JazzCash',
tabInternational:'International',
bankName:'Bank Name',
accountTitle:'Account Title',
accountNo:'Account No.',
branchCode:'Branch Code',
IBAN:'IBAN',
suggestedAmounts:'Suggested Donation Amounts:',
custom:'Custom',
bankNote:'After transfer, send receipt to admin@arainworldcouncil.org or WhatsApp +92-33-9192-9922',
  // Donation confirmation form
  donFormTitle:'Confirm Your Donation',
  donFormSub:'After making the transfer, fill in your details below so we can verify and acknowledge your donation.',
  donorName:'Full Name',
  donorPhone:'Phone / WhatsApp',
  donorEmail:'Email (optional)',
  donAmount:'Amount Donated',
  donMethod:'Payment Method',
  donTxID:'Transaction ID / Reference No.',
  donTxIDPh:'e.g. TXN12345678',
  donNote:'Additional Note (optional)',
  donNotePh:'Any message for the AWC team',
  donProof:'Payment Screenshot (optional)',
  donSubmitBtn:'Submit Donation Record',
  donSubmitting:'Submitting…',
  donSuccess:'Thank you! Your donation record has been received. We will verify and reach out shortly.',
easypaisaNote:'Easypaisa App → Send Money → Mobile Account. Send screenshot after transfer.',
jazzcashNote:'JazzCash App → Send Money → to Mobile. Send screenshot after transfer.',
intNote:'For international transfers allow 3–5 business days. Email admin@arainworldcouncil.org with reference.',
service:'Service',
mobileNo:'Mobile No.',
memAppTitle:'Membership Application — Arain World Council',
memAppSub:'Join with Us! Fill in the form below to become a member of Arain World Council.',
memInstrTitle:'Form Instructions',
memInstr1:'Provide accurate and complete information in all required fields.',
memInstr2:'Your WhatsApp number must be active and accessible.',
memInstr3:'CNIC and Email are optional but correct details are recommended.',
memInstr4:'Our team will contact you after reviewing your application.',
memInstr5:'Incomplete or incorrect information may lead to rejection.',
memNote:'Together We Rise — AWC',
memPersonal:'Personal Information',
memContact:'Contact & Residential',
memProfessional:'Professional Information',
memAddress:'Profile Picture & Address',
memTermsTitle:'Terms and Conditions',
memTerm1:'The information provided is accurate and complete.',
memTerm2:'AWC reserves the right to accept or reject any application.',
memTerm3:'Membership will not be used for political or unlawful purposes.',
memConsent:'I agree to the Membership Terms',
submitApp:'Submit Application',
submitting:'Submitting…',
appSuccess:'Application submitted! Our team will contact you soon.',
msgSuccess:'Message sent successfully!',
sending:'Sending…',
fFullName:'Full Name *',
fFatherName:'Father Name *',
fGender:'Gender *',
fMemberType:'Membership Type *',
fCnic:'CNIC No. / B-Form No.',
fDob:'Date of Birth *',
fEmailF:'Email Address *',
fWhatsapp:'WhatsApp No *',
fResidential:'Residential Status *',
fAffiliated:'Affiliated with any organization? *',
fEducation:'Educational Qualification *',
fWork:'Work Information *',
fReason:'Why do you want to join AWC?',
fPhoto:'Profile Picture',
fStreet:'Street Address *',
fCity:'City *',
fState:'State / Province *',
fCountry:'Country *',
selectOpt:'Select Option',
gFemale:'Female',
gMale:'Male',
gOther:'Other',
mExec:'Executive Member',
mGeneral:'General Member',
mYouth:'Youth Member',
mAssoc:'Associate Member',
rResident:'Resident Pakistani',
rOverseas:'Overseas Pakistani',
yes:'Yes',
no:'No',
eMatric:'Matric',
eInter:'Intermediate',
eGrad:'Graduate',
ePG:'Post Graduate',
eOther:'Other',
wStudent:'Student',
wJob:'Job Holder',
wGov:'Government Employee',
wBiz:'Business Owner',
wFree:'Freelancer',
phFullName:'Muhammad Ali Arain',
phFatherName:'Muhammad Akram Arain',
phCnic:'XXXXX-XXXXXXX-X',
phWhatsapp:'+92XXXXXXXXXX',
phStreet:'House No, Street, Area',
phCity:'Bannu',
phState:'KPK',
phReason:'Share your motivation…',
cPakistan:'Pakistan',
cUSA:'United States of America',
cUK:'United Kingdom',
cCanada:'Canada',
cAustralia:'Australia',
cUAE:'United Arab Emirates',
cSaudi:'Saudi Arabia',
cGermany:'Germany',
cFrance:'France',
cNetherlands:'Netherlands',
cOther:'Other',
langToggleLabel:'اردو',
};

const UR = {
siteName:'ارائیں ورلڈ کونسل',
siteTagline:'اتحاد | بااختیاریت | ترقی',
siteSubName:'بنوں ریجنل آرگنائزیشن',
heroBadge:'AWC میں خوش آمدید',
heroTitle:'ارائیں ورلڈ کونسل',
heroSub:'اپنی اگلی نسل کو بااختیار بنانا، اپنے ورثے پر فخر',
heroTagline:'ارائیں برادری کو عالمی سطح پر متحد کرنا — طاقت، اتحاد، ترقی',
heroAboutBtn:'ہمارے بارے میں',
heroEventsBtn:'خبریں اور تقریبات',
aboutLabel:'ہم کون ہیں',
aboutTitle:'ارائیں ورلڈ کونسل (AWC)',
aboutSubtitle:'فلاح، تعلیم اور بااختیاریت کے ذریعے خدمت',
aboutP1:'ارائیں ورلڈ کونسل ایک غیر سیاسی، فلاحی پلیٹ فارم ہے جو عالمی ارائیں برادری کو ترقی، اتحاد اور بااختیاریت کے ایک وژن کے تحت متحد کرنے کے لیے قائم کیا گیا ہے۔',
aboutP2:'کونسل تعلیم، روزگار، نوجوانوں کی ترقی اور سماجی بہبود جیسے شعبوں میں فعال طور پر کام کرتی ہے۔',
aboutP3:'تمام اراکین بلا امتیاز خلوص اور لگن کے ساتھ رضاکارانہ طور پر معاشرے کی بہتری کے لیے کام کرتے ہیں۔',
statMembersLabel:'اراکین',
statProgramsLabel:'پروگرام',
statCitiesLabel:'شہر',
chairmanBadge:'گلوبل چیئرمین',
joinBtn:'AWC میں شامل ہوں',
programsLabel:'ہم کیا کرتے ہیں',
programsTitle:'پروگرام / اقدامات',
programsDesc:'ہم ذیل کے تمام منصوبوں پر کام کر رہے ہیں۔ ہمارا مقصد پوری ارائیں برادری کو تمام سہولیات فراہم کرنا ہے۔',
teamLabel:'ہماری ٹیم',
leadershipTitle:'ہماری قیادت سے ملیں',
upcomingLabel:'آنے والی',
eventsTitle:'تقریبات اور پروگرام',
touchLabel:'رابطہ کریں',
contactUs:'ہم سے رابطہ کریں',
addressLabel:'پتہ',
hoursLabel:'اوقات کار',
phoneLabel:'فون',
emailLabel:'ای میل',
usefulLinks:'مفید روابط',
recentNews:'تازہ خبریں',
contactUsFooter:'رابطہ کریں',
navHome:'ہوم',
navAbout:'ہمارے بارے میں',
navPrograms:'پروگرام',
navLeadership:'قیادت',
navEvents:'تقریبات',
navContact:'رابطہ',
navMembership:'رکنیت',
navGallery:'گیلری',
heroDept:'محکمے',
heroEvents:'تقریبات',
heroGallery:'گیلری',
heroGuide:'وزیٹرز گائیڈ',
membershipTitle:'رکنیت کے لیے درخواست دیں',
membershipDesc:'خالی سے روشنی تک، راستے بناتے ہوئے جہاں زندہ لمحات پائیدار سفر بن جاتے ہیں۔',
donateTitle:'عطیہ دیں',
donateDesc:'کیا آپ ارائیں خاندان کی مدد کرنا چاہتے ہیں؟',
registerNow:'ابھی رجسٹر کریں',
donateNow:'ابھی عطیہ کریں',
seeAllMembers:'تمام اراکین دیکھیں',
moreDetails:'مزید تفصیل',
formName:'آپ کا نام',
formEmail:'ای میل پتہ',
formSubject:'موضوع',
formMessage:'پیغام',
sendMessage:'پیغام بھیجیں',
phName:'محمد علی ارائیں',
phEmail:'آپ کا ای میل',
phSubject:'مثلاً: رکنیت کی درخواست',
phMessage:'اپنا پیغام یہاں لکھیں…',
galleryTitle:'گیلری',
galleryLabel:'تصویری گیلری',
galleryDesc:'AWC تقریبات اور یادوں کی تصاویر۔',
galleryEmpty:'ابھی کوئی تصویر نہیں۔',
noEvents:'ابھی کوئی تقریب نہیں۔',
noPrograms:'ابھی کوئی پروگرام نہیں۔',
noLeaders:'ابھی کوئی رہنما نہیں۔',
footerDesc:'ارائیں ورلڈ کونسل عالمی ارائیں برادری کو متحد کرتی ہے، نوجوانوں کو بااختیار بناتی ہے، تعلیم کو فروغ دیتی ہے اور دنیا بھر میں ترقی کے لیے مضبوط نیٹ ورک بناتی ہے۔',
footerCopy:'© 2026 ارائیں ورلڈ کونسل (AWC) — جملہ حقوق محفوظ ہیں۔',
news1:'AWC بنوں سالانہ اجتماع 2025',
news2:'نوجوان قائدین اجلاس بنوں 2025',
pageLabBlog:'ہمارا بلاگ',
pageLabHistory:'ہماری تاریخ',
pageLabDocs:'دستاویزات',
pageLabEnv:'ماحولیاتی',
pageLabGallery:'ٹاؤن گیلری',
pageLabDept:'محکمہ',
pageTitleBlog:'AWC بلاگ',
pageTitleHistory:'AWC کی تاریخ',
pageTitleDocs:'AWC دستاویزات',
pageTitleEnv:'AWC ماحولیاتی اقدامات',
pageTitleGallery:'AWC ٹاؤن گیلری',
pageTitleDept:'AWC محکمے',
pageBodyBlog:'AWC بلاگ میں خوش آمدید۔ ارائیں ورلڈ کونسل برادری کی تازہ ترین خبروں، کہانیوں اور اعلانات سے باخبر رہیں۔',
pageBodyHistory:'ارائیں ورلڈ کونسل ارائیں برادری کو عالمی سطح پر متحد کرنے کے وژن کے ساتھ قائم کی گئی۔ معمولی آغاز سے AWC کمیونٹی بااختیاریت اور ترقی کے لیے ایک عالمی تحریک بن گئی ہے۔',
pageBodyDocs:'ارائیں ورلڈ کونسل کی سرکاری دستاویزات، پالیسیاں اور رہنما اصول۔ تمام وسائل اراکین اور عوام کے لیے دستیاب ہیں۔',
pageBodyEnv:'AWC ماحولیاتی تحفظ اور پائیداری کے لیے پرعزم ہے۔ ہم پودے لگانے، صاف پانی کے اقدامات اور ماحول دوست پروگراموں کو فروغ دیتے ہیں۔',
pageBodyGallery:'دنیا بھر کے شہروں میں AWC تقریبات، کمیونٹی اجتماعات اور سنگ میل سے تصاویر اور یادیں دیکھیں۔',
pageBodyDept:'AWC متعدد محکموں کے ذریعے کام کرتی ہے جن میں تعلیم، بہبود، نوجوانوں کے امور، خواتین کی بااختیاریت اور بین الاقوامی تعلقات شامل ہیں۔',
donateToAWC:'AWC کو عطیہ دیں',
donSub:'آپ کا عطیہ براہ راست ارائیں برادری کی مدد کرتا ہے۔',
tabBank:'بینک ٹرانسفر',
tabEasypaisa:'Easypaisa',
tabJazzcash:'JazzCash',
tabInternational:'بین الاقوامی',
bankName:'بینک کا نام',
accountTitle:'اکاؤنٹ کا عنوان',
accountNo:'اکاؤنٹ نمبر',
branchCode:'برانچ کوڈ',
IBAN:'IBAN',
suggestedAmounts:'تجویز کردہ عطیہ:',
custom:'اپنی رقم',
bankNote:'منتقلی کے بعد رسید ای میل یا واٹس ایپ پر بھیجیں۔',
  donFormTitle:'اپنا عطیہ درج کریں',
  donFormSub:'رقم منتقل کرنے کے بعد اپنی تفصیلات درج کریں تاکہ ہم تصدیق کر سکیں۔',
  donorName:'پورا نام',
  donorPhone:'فون / واٹس ایپ',
  donorEmail:'ای میل (اختیاری)',
  donAmount:'عطیہ کی رقم',
  donMethod:'ادائیگی کا طریقہ',
  donTxID:'ٹرانزیکشن آئی ڈی / حوالہ نمبر',
  donTxIDPh:'مثال: TXN12345678',
  donNote:'اضافی نوٹ (اختیاری)',
  donNotePh:'AWC ٹیم کے لیے کوئی پیغام',
  donProof:'ادائیگی کا اسکرین شاٹ (اختیاری)',
  donSubmitBtn:'عطیہ ریکارڈ جمع کریں',
  donSubmitting:'جمع ہو رہا ہے…',
  donSuccess:'شکریہ! آپ کا عطیہ ریکارڈ موصول ہو گیا۔ ہم جلد تصدیق کر کے رابطہ کریں گے۔',
easypaisaNote:'Easypaisa ایپ ← پیسے بھیجیں ← موبائل اکاؤنٹ۔ منتقلی کے بعد اسکرین شاٹ بھیجیں۔',
jazzcashNote:'JazzCash ایپ ← پیسے بھیجیں ← موبائل پر۔ منتقلی کے بعد اسکرین شاٹ بھیجیں۔',
intNote:'بین الاقوامی ٹرانسفر کے لیے 3-5 کاروباری دن لگتے ہیں۔ حوالہ نمبر کے ساتھ ای میل کریں۔',
service:'سروس',
mobileNo:'موبائل نمبر',
memAppTitle:'رکنیت کی درخواست — ارائیں ورلڈ کونسل',
memAppSub:'ہمارے ساتھ شامل ہوں! ارائیں ورلڈ کونسل کے رکن بننے کے لیے نیچے فارم بھریں۔',
memInstrTitle:'فارم ہدایات',
memInstr1:'تمام ضروری خانوں میں درست اور مکمل معلومات فراہم کریں۔',
memInstr2:'آپ کا واٹس ایپ نمبر فعال ہونا چاہیے۔',
memInstr3:'شناختی کارڈ اور ای میل اختیاری ہیں لیکن درست تفصیلات تجویز کی جاتی ہیں۔',
memInstr4:'ہماری ٹیم جائزے کے بعد آپ سے رابطہ کرے گی۔',
memInstr5:'ادھوری معلومات رد کا سبب بن سکتی ہے۔',
memNote:'مل کر ترقی کریں — AWC',
memPersonal:'ذاتی معلومات',
memContact:'رابطہ اور رہائشی',
memProfessional:'پیشہ ورانہ معلومات',
memAddress:'پروفائل تصویر اور پتہ',
memTermsTitle:'شرائط و ضوابط',
memTerm1:'فراہم کردہ معلومات درست اور مکمل ہیں۔',
memTerm2:'AWC کسی بھی درخواست کو قبول یا رد کرنے کا حق رکھتی ہے۔',
memTerm3:'رکنیت سیاسی یا غیر قانونی مقاصد کے لیے استعمال نہیں ہوگی۔',
memConsent:'میں رکنیت کی شرائط سے متفق ہوں',
submitApp:'درخواست جمع کرائیں',
submitting:'بھیجا جا رہا ہے…',
appSuccess:'آپ کی درخواست کامیابی سے جمع ہو گئی! ہماری ٹیم جلد آپ سے رابطہ کرے گی۔',
msgSuccess:'پیغام کامیابی سے بھیج دیا گیا!',
sending:'بھیجا جا رہا ہے…',
fFullName:'پورا نام *',
fFatherName:'والد کا نام *',
fGender:'جنس *',
fMemberType:'رکنیت کی قسم *',
fCnic:'شناختی کارڈ نمبر',
fDob:'تاریخ پیدائش *',
fEmailF:'ای میل *',
fWhatsapp:'واٹس ایپ نمبر *',
fResidential:'رہائشی حیثیت *',
fAffiliated:'کسی تنظیم سے وابستہ؟ *',
fEducation:'تعلیمی قابلیت *',
fWork:'کام کی معلومات *',
fReason:'آپ AWC میں کیوں شامل ہونا چاہتے ہیں؟',
fPhoto:'پروفائل تصویر',
fStreet:'گلی کا پتہ *',
fCity:'شہر *',
fState:'صوبہ *',
fCountry:'ملک *',
selectOpt:'آپشن منتخب کریں',
gFemale:'خاتون',
gMale:'مرد',
gOther:'دیگر',
mExec:'ایگزیکٹو رکن',
mGeneral:'عام رکن',
mYouth:'نوجوان رکن',
mAssoc:'ایسوسی ایٹ رکن',
rResident:'مقیم پاکستانی',
rOverseas:'بیرون ملک پاکستانی',
yes:'ہاں',
no:'نہیں',
eMatric:'میٹرک',
eInter:'انٹرمیڈیٹ',
eGrad:'گریجویٹ',
ePG:'پوسٹ گریجویٹ',
eOther:'دیگر',
wStudent:'طالب علم',
wJob:'ملازم',
wGov:'سرکاری ملازم',
wBiz:'کاروباری',
wFree:'فری لانسر',
phFullName:'محمد علی ارائیں',
phFatherName:'محمد اکرم ارائیں',
phCnic:'XXXXX-XXXXXXX-X',
phWhatsapp:'+92XXXXXXXXXX',
phStreet:'مکان نمبر، گلی، علاقہ',
phCity:'بنوں',
phState:'خیبر پختونخوا',
phReason:'اپنی وجہ بیان کریں…',
cPakistan:'پاکستان',
cUSA:'امریکہ',
cUK:'برطانیہ',
cCanada:'کینیڈا',
cAustralia:'آسٹریلیا',
cUAE:'متحدہ عرب امارات',
cSaudi:'سعودی عرب',
cGermany:'جرمنی',
cFrance:'فرانس',
cNetherlands:'نیدرلینڈز',
cOther:'دیگر',
langToggleLabel:'English',
};

await i18next.init({
  lng: localStorage.getItem('awc_lang') || 'ur',
  // No fallbackLng — each language is self-contained.
  // If a key is missing in the active language, t() below falls back
  // to that SAME language's own dictionary lookup, never the other language,
  // so the page never silently mixes English and Urdu together.
  fallbackLng: false,
  resources: {
    en: { translation: EN },
    ur: { translation: UR },
  },
  interpolation: { escapeValue: false },
  returnEmptyString: false,
  returnNull: false,
});

// ── t(key, lang) — same signature app.js already calls ──────────
// Switches i18next's active language on the fly if it differs
// from what's currently loaded, then returns the translated string.
// Falls back to the raw key if no translation exists (matches old behaviour).
export function t(key, lang) {
  if (lang && i18next.language !== lang) {
    i18next.changeLanguage(lang);
  }
  const val = i18next.t(key);
  if (val !== key) return val;
  // Missing from i18next's active bundle — fall back to the SAME
  // language's own raw dictionary (never the other language),
  // so a missing Urdu key never silently shows English, or vice versa.
  const dict = (lang || i18next.language) === 'ur' ? UR : EN;
  return dict[key] || key;
}

// ── Exported for any code still doing direct dictionary lookups ──
export { EN, UR };
