// ================================================================
//  js/lang.js  —  Translation source dictionary
//  ARAAIN BANNU
//
//  EN is the single source of truth for all UI strings.
//  The UR (Urdu) dictionary has been removed — translations are
//  now fetched from the MyMemory API and stored permanently in
//  localStorage (see js/translate.js).
//
//  Cache key:  ab_translations_780a90fb
//  Bust cache: change any EN value → hash changes → auto re-fetch
//
//  Usage in app.js:
//    t('key', lang)  →  EN string (en) or cached Urdu (ur)
//    tv('key')       →  cloud S[key] or EN/cached Urdu fallback
// ================================================================

// ── English source dictionary (216 keys) ─────────────────────
export const EN = {
siteName:'ARAAIN BANNU',
siteTagline:'Unity | Empowerment | Development',
siteSubName:'Bannu Regional Organisation',
heroBadge:'Welcome to ARAAIN BANNU',
heroTitle:'ARAAIN BANNU',
heroSub:'Empowering Our Next Generation, Proud Of Our Heritage',
heroTagline:'Uniting the Arain Community Worldwide — A Global Platform for Arain Excellence | Strength, Unity, Progress',
heroAboutBtn:'About Us',
heroEventsBtn:'News & Events',
aboutLabel:'Who We Are',
aboutTitle:'ARAAIN BANNU',
aboutSubtitle:'Serving Communities Through Welfare, Education, and Empowerment',
aboutP1:'ARAAIN BANNU is a non-political, welfare-oriented platform established to unite the global Arain community under one vision of progress, unity, and empowerment.',
aboutP2:'The Council actively works in key areas such as education, employment, youth development, and social welfare.',
aboutP3:'All members contribute voluntarily with dedication and sincerity. The Council believes in transparency, unity, and service to humanity.',
statMembersLabel:'Members',
statProgramsLabel:'Programs',
statCitiesLabel:'Cities',
chairmanBadge:'Global Chairman',
joinBtn:'Join ARAAIN BANNU',
programsLabel:'What We Do',
programsTitle:'Programs / Initiatives',
programsDesc:'We work on all the projects below. Our goal is to provide all facilities to the entire Arain community.',
teamLabel:'Our Team',
leadershipTitle:'Meet Our Leadership',
upcomingLabel:'Upcoming',
eventsTitle:'Events & Programs',
touchLabel:'Get In Touch',
contactUs:'Contact Us',
addressLabel:'Address',
hoursLabel:'Opening Hours',
phoneLabel:'Phone',
emailLabel:'Email',
usefulLinks:'Useful Links',
recentNews:'Recent News',
contactUsFooter:'Contact Us',
navHome:'Home',
navAbout:'About Us',
navPrograms:'Programs',
navLeadership:'Leadership',
navEvents:'Events',
navContact:'Contact',
navMembership:'Membership',
navGallery:'Gallery',
heroDept:'Departments',
heroEvents:'Events',
heroGallery:'Gallery',
heroGuide:'Visitors Guide',
membershipTitle:'Apply Membership',
membershipDesc:'From void to light, shaping paths where living moments turn into lasting journeys.',
donateTitle:'Give Donation',
donateDesc:'Do you want to support the Arain Family and make a meaningful difference?',
registerNow:'Register Now',
donateNow:'Donate Now',
seeAllMembers:'See All Members',
moreDetails:'More Details',
formName:'Your Name',
formEmail:'Email Address',
formSubject:'Subject',
formMessage:'Message',
sendMessage:'Send Message',
phName:'Muhammad Ali Arain',
phEmail:'you@example.com',
phSubject:'e.g. Membership Inquiry',
phMessage:'Write your message here…',
galleryTitle:'Gallery',
galleryLabel:'Photo Gallery',
galleryDesc:'Memories from ARAAIN BANNU events and milestones.',
galleryEmpty:'No photos yet.',
noEvents:'No events yet.',
noPrograms:'No programs yet.',
noLeaders:'No leaders yet.',
footerDesc:'ARAAIN BANNU unites the global Arain community, empowering youth, promoting education, supporting welfare, and building strong networks for progress worldwide.',
footerCopy:'© 2026 ARAAIN BANNU — All Rights Reserved.',
news1:'ARAAIN BANNU Annual Gathering 2025',
news2:'Youth Leadership Summit Bannu 2025',
pageLabBlog:'Our Blog',
pageLabHistory:'Our History',
pageLabDocs:'Documentation',
pageLabEnv:'Environmental',
pageLabGallery:'Town Gallery',
pageLabDept:'Department',
pageTitleBlog:'ARAAIN BANNU Blog',
pageTitleHistory:'ARAAIN BANNU History',
pageTitleDocs:'ARAAIN BANNU Documentation',
pageTitleEnv:'ARAAIN BANNU Environmental Initiatives',
pageTitleGallery:'ARAAIN BANNU Gallery',
pageTitleDept:'ARAAIN BANNU Departments',
pageBodyBlog:'Welcome to the ARAAIN BANNU Blog. Stay updated with the latest news, stories, and announcements from the ARAAIN BANNU community.',
pageBodyHistory:'The ARAAIN BANNU was founded with a vision to unite Arains globally. From humble beginnings, ARAAIN BANNU has grown into a worldwide movement for community empowerment and development.',
pageBodyDocs:'Official documents, policies, and guidelines of the ARAAIN BANNU. All resources are available for members and the public.',
pageBodyEnv:'ARAAIN BANNU is committed to environmental protection and sustainability. We promote tree planting, clean water initiatives, and eco-friendly community programs.',
pageBodyGallery:'Explore photos and memories from ARAAIN BANNU events, community gatherings, and milestones across cities and countries.',
pageBodyDept:'ARAAIN BANNU operates through multiple departments including Education, Welfare, Youth Affairs, Women Empowerment, and International Relations.',
donateToAraainBannu:'Donate to ARAAIN BANNU',
donSub:'Your donation directly supports the Arain community. Transfer to our verified accounts below.',
tabBank:'Bank Transfer',
tabEasypaisa:'Easypaisa',
tabJazzcash:'JazzCash',
tabInternational:'International',
bankName:'Bank Name',
accountTitle:'Account Title',
accountNo:'Account No.',
branchCode:'Branch Code',
IBAN:'IBAN',
suggestedAmounts:'Suggested Donation Amounts:',
custom:'Custom',
bankNote:'After transfer, send receipt to admin@arainworldcouncil.org or WhatsApp +92-33-9192-9922',
  // Donation confirmation form
  donFormTitle:'Confirm Your Donation',
  donFormSub:'After making the transfer, fill in your details below so we can verify and acknowledge your donation.',
  donorName:'Full Name',
  donorPhone:'Phone / WhatsApp',
  donorEmail:'Email (optional)',
  donAmount:'Amount Donated',
  donMethod:'Payment Method',
  donTxID:'Transaction ID / Reference No.',
  donTxIDPh:'e.g. TXN12345678',
  donNote:'Additional Note (optional)',
  donNotePh:'Any message for the ARAAIN BANNU team',
  donProof:'Payment Screenshot (optional)',
  donSubmitBtn:'Submit Donation Record',
  donSubmitting:'Submitting…',
  donSuccess:'Thank you! Your donation record has been received. We will verify and reach out shortly.',
easypaisaNote:'Easypaisa App → Send Money → Mobile Account. Send screenshot after transfer.',
jazzcashNote:'JazzCash App → Send Money → to Mobile. Send screenshot after transfer.',
intNote:'For international transfers allow 3–5 business days. Email admin@arainworldcouncil.org with reference.',
service:'Service',
mobileNo:'Mobile No.',
memAppTitle:'Membership Application — ARAAIN BANNU',
memAppSub:'Join with Us! Fill in the form below to become a member of ARAAIN BANNU.',
memInstrTitle:'Form Instructions',
memInstr1:'Provide accurate and complete information in all required fields.',
memInstr2:'Your WhatsApp number must be active and accessible.',
memInstr3:'CNIC and Email are optional but correct details are recommended.',
memInstr4:'Our team will contact you after reviewing your application.',
memInstr5:'Incomplete or incorrect information may lead to rejection.',
memNote:'Together We Rise — ARAAIN BANNU',
memPersonal:'Personal Information',
memContact:'Contact & Residential',
memProfessional:'Professional Information',
memAddress:'Profile Picture & Address',
memTermsTitle:'Terms and Conditions',
memTerm1:'The information provided is accurate and complete.',
memTerm2:'ARAAIN BANNU reserves the right to accept or reject any application.',
memTerm3:'Membership will not be used for political or unlawful purposes.',
memConsent:'I agree to the Membership Terms',
submitApp:'Submit Application',
submitting:'Submitting…',
appSuccess:'Application submitted! Our team will contact you soon.',
msgSuccess:'Message sent successfully!',
sending:'Sending…',
fFullName:'Full Name *',
fFatherName:'Father Name *',
fGender:'Gender *',
fMemberType:'Membership Type *',
fCnic:'CNIC No. / B-Form No.',
fDob:'Date of Birth *',
fEmailF:'Email Address *',
fWhatsapp:'WhatsApp No *',
fResidential:'Residential Status *',
fAffiliated:'Affiliated with any organization? *',
fEducation:'Educational Qualification *',
fWork:'Work Information *',
fReason:'Why do you want to join ARAAIN BANNU?',
fPhoto:'Profile Picture',
fStreet:'Street Address *',
fCity:'City *',
fState:'State / Province *',
fCountry:'Country *',
selectOpt:'Select Option',
gFemale:'Female',
gMale:'Male',
gOther:'Other',
mExec:'Executive Member',
mGeneral:'General Member',
mYouth:'Youth Member',
mAssoc:'Associate Member',
rResident:'Resident Pakistani',
rOverseas:'Overseas Pakistani',
yes:'Yes',
no:'No',
eMatric:'Matric',
eInter:'Intermediate',
eGrad:'Graduate',
ePG:'Post Graduate',
eOther:'Other',
wStudent:'Student',
wJob:'Job Holder',
wGov:'Government Employee',
wBiz:'Business Owner',
wFree:'Freelancer',
phFullName:'Muhammad Ali Arain',
phFatherName:'Muhammad Akram Arain',
phCnic:'XXXXX-XXXXXXX-X',
phWhatsapp:'+92XXXXXXXXXX',
phStreet:'House No, Street, Area',
phCity:'Bannu',
phState:'KPK',
phReason:'Share your motivation…',
cPakistan:'Pakistan',
cUSA:'United States of America',
cUK:'United Kingdom',
cCanada:'Canada',
cAustralia:'Australia',
cUAE:'United Arab Emirates',
cSaudi:'Saudi Arabia',
cGermany:'Germany',
cFrance:'France',
cNetherlands:'Netherlands',
cOther:'Other',  chairmanName:'Tahir Meer',
  chairmanQuote:'Unity, Empowerment, and Development — the three pillars of ARAAIN BANNU.',

  contactAddressDefault:'Bannu, Khyber Pakhtunkhwa, Pakistan',
  contactHoursDefault:'Mon – Fri: 8:00 am – 6:00 pm',
  contactEmailDefault:'admin@arainbannu.org',
  contactPhoneDefault:'+92-33-9192-9922',

langToggleLabel:'اردو',
};

// ── Keys that are never translated (brands, formats, numbers) ─
export const NO_TRANSLATE = new Set(['IBAN', 'contactEmailDefault', 'contactPhoneDefault', 'langToggleLabel', 'phCnic', 'phWhatsapp', 'swiftBic', 'tabEasypaisa', 'tabJazzcash']);

// ── Cache version — tied to EN dict content hash ───────────────
export const DICT_HASH = '780a90fb';

// ── t(key, lang) — reads from persistent Urdu cache ───────────
// The `_urCache` Map is populated by translate.js on first Urdu
// load and reloaded from localStorage on every subsequent visit.
// Until the cache is ready, EN[key] is returned as a fallback
// so the page always renders something immediately.
let _urCache = new Map();

export function setUrCache(map) {
  _urCache = map;
}

export function t(key, lang) {
  if (lang !== 'ur') return EN[key] !== undefined ? EN[key] : key;
  return _urCache.get(key) || EN[key] || key;
}
