// ================================================================
//  js/lang.js  —  Synchronous bilingual dictionary
//  ARAAIN BANNU — Bannu Regional Organisation
//
//  Languages: English (en) and Urdu (ur)
//  Usage:  t('key', lang)     → translated string
//          tv('key')          → in app.js, uses module-level `lang`
//  Both dictionaries have identical keys (211 total).
//  If a key is missing in the active language the same language's
//  own dictionary is checked first — never silently crossed.
// ================================================================

// ── English dictionary ───────────────────────────────────────
export const EN = {
siteName:'ARAAIN BANNU',
siteTagline:'Unity | Empowerment | Development',
siteSubName:'Bannu Regional Organisation',
heroBadge:'Welcome to ARAAIN BANNU',
heroTitle:'ARAAIN BANNU',
heroSub:'Empowering Our Next Generation, Proud Of Our Heritage',
heroTagline:'Uniting the Arain Community Worldwide — A Global Platform for Arain Excellence | Strength, Unity, Progress',
heroAboutBtn:'About Us',
heroEventsBtn:'News & Events',
aboutLabel:'Who We Are',
aboutTitle:'ARAAIN BANNU',
aboutSubtitle:'Serving Communities Through Welfare, Education, and Empowerment',
aboutP1:'ARAAIN BANNU is a non-political, welfare-oriented platform established to unite the global Arain community under one vision of progress, unity, and empowerment.',
aboutP2:'The Council actively works in key areas such as education, employment, youth development, and social welfare.',
aboutP3:'All members contribute voluntarily with dedication and sincerity. The Council believes in transparency, unity, and service to humanity.',
statMembersLabel:'Members',
statProgramsLabel:'Programs',
statCitiesLabel:'Cities',
chairmanBadge:'Global Chairman',
joinBtn:'Join ARAAIN BANNU',
programsLabel:'What We Do',
programsTitle:'Programs / Initiatives',
programsDesc:'We work on all the projects below. Our goal is to provide all facilities to the entire Arain community.',
teamLabel:'Our Team',
leadershipTitle:'Meet Our Leadership',
upcomingLabel:'Upcoming',
eventsTitle:'Events & Programs',
touchLabel:'Get In Touch',
contactUs:'Contact Us',
addressLabel:'Address',
hoursLabel:'Opening Hours',
phoneLabel:'Phone',
emailLabel:'Email',
usefulLinks:'Useful Links',
recentNews:'Recent News',
contactUsFooter:'Contact Us',
navHome:'Home',
navAbout:'About Us',
navPrograms:'Programs',
navLeadership:'Leadership',
navEvents:'Events',
navContact:'Contact',
navMembership:'Membership',
navGallery:'Gallery',
heroDept:'Departments',
heroEvents:'Events',
heroGallery:'Gallery',
heroGuide:'Visitors Guide',
membershipTitle:'Apply Membership',
membershipDesc:'From void to light, shaping paths where living moments turn into lasting journeys.',
donateTitle:'Give Donation',
donateDesc:'Do you want to support the Arain Family and make a meaningful difference?',
registerNow:'Register Now',
donateNow:'Donate Now',
seeAllMembers:'See All Members',
moreDetails:'More Details',
formName:'Your Name',
formEmail:'Email Address',
formSubject:'Subject',
formMessage:'Message',
sendMessage:'Send Message',
phName:'Muhammad Ali Arain',
phEmail:'you@example.com',
phSubject:'e.g. Membership Inquiry',
phMessage:'Write your message here…',
galleryTitle:'Gallery',
galleryLabel:'Photo Gallery',
galleryDesc:'Memories from ARAAIN BANNU events and milestones.',
galleryEmpty:'No photos yet.',
noEvents:'No events yet.',
noPrograms:'No programs yet.',
noLeaders:'No leaders yet.',
footerDesc:'ARAAIN BANNU unites the global Arain community, empowering youth, promoting education, supporting welfare, and building strong networks for progress worldwide.',
footerCopy:'© 2026 ARAAIN BANNU — All Rights Reserved.',
news1:'ARAAIN BANNU Annual Gathering 2025',
news2:'Youth Leadership Summit Bannu 2025',
pageLabBlog:'Our Blog',
pageLabHistory:'Our History',
pageLabDocs:'Documentation',
pageLabEnv:'Environmental',
pageLabGallery:'Town Gallery',
pageLabDept:'Department',
pageTitleBlog:'ARAAIN BANNU Blog',
pageTitleHistory:'ARAAIN BANNU History',
pageTitleDocs:'ARAAIN BANNU Documentation',
pageTitleEnv:'ARAAIN BANNU Environmental Initiatives',
pageTitleGallery:'ARAAIN BANNU Gallery',
pageTitleDept:'ARAAIN BANNU Departments',
pageBodyBlog:'Welcome to the ARAAIN BANNU Blog. Stay updated with the latest news, stories, and announcements from the ARAAIN BANNU community.',
pageBodyHistory:'The ARAAIN BANNU was founded with a vision to unite Arains globally. From humble beginnings, ARAAIN BANNU has grown into a worldwide movement for community empowerment and development.',
pageBodyDocs:'Official documents, policies, and guidelines of the ARAAIN BANNU. All resources are available for members and the public.',
pageBodyEnv:'ARAAIN BANNU is committed to environmental protection and sustainability. We promote tree planting, clean water initiatives, and eco-friendly community programs.',
pageBodyGallery:'Explore photos and memories from ARAAIN BANNU events, community gatherings, and milestones across cities and countries.',
pageBodyDept:'ARAAIN BANNU operates through multiple departments including Education, Welfare, Youth Affairs, Women Empowerment, and International Relations.',
donateToAraainBannu:'Donate to ARAAIN BANNU',
donSub:'Your donation directly supports the Arain community. Transfer to our verified accounts below.',
tabBank:'Bank Transfer',
tabEasypaisa:'Easypaisa',
tabJazzcash:'JazzCash',
tabInternational:'International',
bankName:'Bank Name',
accountTitle:'Account Title',
accountNo:'Account No.',
branchCode:'Branch Code',
IBAN:'IBAN',
suggestedAmounts:'Suggested Donation Amounts:',
custom:'Custom',
bankNote:'After transfer, send receipt to admin@arainworldcouncil.org or WhatsApp +92-33-9192-9922',
  // Donation confirmation form
  donFormTitle:'Confirm Your Donation',
  donFormSub:'After making the transfer, fill in your details below so we can verify and acknowledge your donation.',
  donorName:'Full Name',
  donorPhone:'Phone / WhatsApp',
  donorEmail:'Email (optional)',
  donAmount:'Amount Donated',
  donMethod:'Payment Method',
  donTxID:'Transaction ID / Reference No.',
  donTxIDPh:'e.g. TXN12345678',
  donNote:'Additional Note (optional)',
  donNotePh:'Any message for the ARAAIN BANNU team',
  donProof:'Payment Screenshot (optional)',
  donSubmitBtn:'Submit Donation Record',
  donSubmitting:'Submitting…',
  donSuccess:'Thank you! Your donation record has been received. We will verify and reach out shortly.',
easypaisaNote:'Easypaisa App → Send Money → Mobile Account. Send screenshot after transfer.',
jazzcashNote:'JazzCash App → Send Money → to Mobile. Send screenshot after transfer.',
intNote:'For international transfers allow 3–5 business days. Email admin@arainworldcouncil.org with reference.',
service:'Service',
mobileNo:'Mobile No.',
memAppTitle:'Membership Application — ARAAIN BANNU',
memAppSub:'Join with Us! Fill in the form below to become a member of ARAAIN BANNU.',
memInstrTitle:'Form Instructions',
memInstr1:'Provide accurate and complete information in all required fields.',
memInstr2:'Your WhatsApp number must be active and accessible.',
memInstr3:'CNIC and Email are optional but correct details are recommended.',
memInstr4:'Our team will contact you after reviewing your application.',
memInstr5:'Incomplete or incorrect information may lead to rejection.',
memNote:'Together We Rise — ARAAIN BANNU',
memPersonal:'Personal Information',
memContact:'Contact & Residential',
memProfessional:'Professional Information',
memAddress:'Profile Picture & Address',
memTermsTitle:'Terms and Conditions',
memTerm1:'The information provided is accurate and complete.',
memTerm2:'ARAAIN BANNU reserves the right to accept or reject any application.',
memTerm3:'Membership will not be used for political or unlawful purposes.',
memConsent:'I agree to the Membership Terms',
submitApp:'Submit Application',
submitting:'Submitting…',
appSuccess:'Application submitted! Our team will contact you soon.',
msgSuccess:'Message sent successfully!',
sending:'Sending…',
fFullName:'Full Name *',
fFatherName:'Father Name *',
fGender:'Gender *',
fMemberType:'Membership Type *',
fCnic:'CNIC No. / B-Form No.',
fDob:'Date of Birth *',
fEmailF:'Email Address *',
fWhatsapp:'WhatsApp No *',
fResidential:'Residential Status *',
fAffiliated:'Affiliated with any organization? *',
fEducation:'Educational Qualification *',
fWork:'Work Information *',
fReason:'Why do you want to join ARAAIN BANNU?',
fPhoto:'Profile Picture',
fStreet:'Street Address *',
fCity:'City *',
fState:'State / Province *',
fCountry:'Country *',
selectOpt:'Select Option',
gFemale:'Female',
gMale:'Male',
gOther:'Other',
mExec:'Executive Member',
mGeneral:'General Member',
mYouth:'Youth Member',
mAssoc:'Associate Member',
rResident:'Resident Pakistani',
rOverseas:'Overseas Pakistani',
yes:'Yes',
no:'No',
eMatric:'Matric',
eInter:'Intermediate',
eGrad:'Graduate',
ePG:'Post Graduate',
eOther:'Other',
wStudent:'Student',
wJob:'Job Holder',
wGov:'Government Employee',
wBiz:'Business Owner',
wFree:'Freelancer',
phFullName:'Muhammad Ali Arain',
phFatherName:'Muhammad Akram Arain',
phCnic:'XXXXX-XXXXXXX-X',
phWhatsapp:'+92XXXXXXXXXX',
phStreet:'House No, Street, Area',
phCity:'Bannu',
phState:'KPK',
phReason:'Share your motivation…',
cPakistan:'Pakistan',
cUSA:'United States of America',
cUK:'United Kingdom',
cCanada:'Canada',
cAustralia:'Australia',
cUAE:'United Arab Emirates',
cSaudi:'Saudi Arabia',
cGermany:'Germany',
cFrance:'France',
cNetherlands:'Netherlands',
cOther:'Other',  chairmanName:'Tahir Meer',
  chairmanQuote:'Unity, Empowerment, and Development — the three pillars of ARAAIN BANNU.',

  contactAddressDefault:'Bannu, Khyber Pakhtunkhwa, Pakistan',
  contactHoursDefault:'Mon – Fri: 8:00 am – 6:00 pm',
  contactEmailDefault:'admin@arainbannu.org',
  contactPhoneDefault:'+92-33-9192-9922',

langToggleLabel:'اردو',
};

// ── Urdu dictionary ──────────────────────────────────────────
export const UR = {
siteName:'ارائیں بنوں',
siteTagline:'اتحاد | بااختیاریت | ترقی',
siteSubName:'بنوں ریجنل آرگنائزیشن',
heroBadge:'ارائیں بنوں میں خوش آمدید',
heroTitle:'ارائیں بنوں',
heroSub:'اپنی اگلی نسل کو بااختیار بنانا، اپنے ورثے پر فخر',
heroTagline:'ارائیں برادری کو عالمی سطح پر متحد کرنا — طاقت، اتحاد، ترقی',
heroAboutBtn:'ہمارے بارے میں',
heroEventsBtn:'خبریں اور تقریبات',
aboutLabel:'ہم کون ہیں',
aboutTitle:'ارائیں بنوں (ارائیں بنوں)',
aboutSubtitle:'فلاح، تعلیم اور بااختیاریت کے ذریعے خدمت',
aboutP1:'ارائیں بنوں ایک غیر سیاسی، فلاحی پلیٹ فارم ہے جو عالمی ارائیں برادری کو ترقی، اتحاد اور بااختیاریت کے ایک وژن کے تحت متحد کرنے کے لیے قائم کیا گیا ہے۔',
aboutP2:'کونسل تعلیم، روزگار، نوجوانوں کی ترقی اور سماجی بہبود جیسے شعبوں میں فعال طور پر کام کرتی ہے۔',
aboutP3:'تمام اراکین بلا امتیاز خلوص اور لگن کے ساتھ رضاکارانہ طور پر معاشرے کی بہتری کے لیے کام کرتے ہیں۔',
statMembersLabel:'اراکین',
statProgramsLabel:'پروگرام',
statCitiesLabel:'شہر',
chairmanBadge:'گلوبل چیئرمین',
joinBtn:'ارائیں بنوں میں شامل ہوں',
programsLabel:'ہم کیا کرتے ہیں',
programsTitle:'پروگرام / اقدامات',
programsDesc:'ہم ذیل کے تمام منصوبوں پر کام کر رہے ہیں۔ ہمارا مقصد پوری ارائیں برادری کو تمام سہولیات فراہم کرنا ہے۔',
teamLabel:'ہماری ٹیم',
leadershipTitle:'ہماری قیادت سے ملیں',
upcomingLabel:'آنے والی',
eventsTitle:'تقریبات اور پروگرام',
touchLabel:'رابطہ کریں',
contactUs:'ہم سے رابطہ کریں',
addressLabel:'پتہ',
hoursLabel:'اوقات کار',
phoneLabel:'فون',
emailLabel:'ای میل',
usefulLinks:'مفید روابط',
recentNews:'تازہ خبریں',
contactUsFooter:'رابطہ کریں',
navHome:'ہوم',
navAbout:'ہمارے بارے میں',
navPrograms:'پروگرام',
navLeadership:'قیادت',
navEvents:'تقریبات',
navContact:'رابطہ',
navMembership:'رکنیت',
navGallery:'گیلری',
heroDept:'محکمے',
heroEvents:'تقریبات',
heroGallery:'گیلری',
heroGuide:'وزیٹرز گائیڈ',
membershipTitle:'رکنیت کے لیے درخواست دیں',
membershipDesc:'خالی سے روشنی تک، راستے بناتے ہوئے جہاں زندہ لمحات پائیدار سفر بن جاتے ہیں۔',
donateTitle:'عطیہ دیں',
donateDesc:'کیا آپ ارائیں خاندان کی مدد کرنا چاہتے ہیں؟',
registerNow:'ابھی رجسٹر کریں',
donateNow:'ابھی عطیہ کریں',
seeAllMembers:'تمام اراکین دیکھیں',
moreDetails:'مزید تفصیل',
formName:'آپ کا نام',
formEmail:'ای میل پتہ',
formSubject:'موضوع',
formMessage:'پیغام',
sendMessage:'پیغام بھیجیں',
phName:'محمد علی ارائیں',
phEmail:'آپ کا ای میل',
phSubject:'مثلاً: رکنیت کی درخواست',
phMessage:'اپنا پیغام یہاں لکھیں…',
galleryTitle:'گیلری',
galleryLabel:'تصویری گیلری',
galleryDesc:'ارائیں بنوں تقریبات اور یادوں کی تصاویر۔',
galleryEmpty:'ابھی کوئی تصویر نہیں۔',
noEvents:'ابھی کوئی تقریب نہیں۔',
noPrograms:'ابھی کوئی پروگرام نہیں۔',
noLeaders:'ابھی کوئی رہنما نہیں۔',
footerDesc:'ارائیں بنوں عالمی ارائیں برادری کو متحد کرتی ہے، نوجوانوں کو بااختیار بناتی ہے، تعلیم کو فروغ دیتی ہے اور دنیا بھر میں ترقی کے لیے مضبوط نیٹ ورک بناتی ہے۔',
footerCopy:'© 2026 ارائیں بنوں (ارائیں بنوں) — جملہ حقوق محفوظ ہیں۔',
news1:'ارائیں بنوں سالانہ اجتماع 2025',
news2:'نوجوان قائدین اجلاس بنوں 2025',
pageLabBlog:'ہمارا بلاگ',
pageLabHistory:'ہماری تاریخ',
pageLabDocs:'دستاویزات',
pageLabEnv:'ماحولیاتی',
pageLabGallery:'ٹاؤن گیلری',
pageLabDept:'محکمہ',
pageTitleBlog:'ارائیں بنوں بلاگ',
pageTitleHistory:'ارائیں بنوں کی تاریخ',
pageTitleDocs:'ارائیں بنوں دستاویزات',
pageTitleEnv:'ارائیں بنوں ماحولیاتی اقدامات',
pageTitleGallery:'ارائیں بنوں گیلری',
pageTitleDept:'ارائیں بنوں محکمے',
pageBodyBlog:'ارائیں بنوں بلاگ میں خوش آمدید۔ ارائیں بنوں برادری کی تازہ ترین خبروں، کہانیوں اور اعلانات سے باخبر رہیں۔',
pageBodyHistory:'ارائیں بنوں ارائیں برادری کو عالمی سطح پر متحد کرنے کے وژن کے ساتھ قائم کی گئی۔ معمولی آغاز سے ارائیں بنوں کمیونٹی بااختیاریت اور ترقی کے لیے ایک عالمی تحریک بن گئی ہے۔',
pageBodyDocs:'ارائیں بنوں کی سرکاری دستاویزات، پالیسیاں اور رہنما اصول۔ تمام وسائل اراکین اور عوام کے لیے دستیاب ہیں۔',
pageBodyEnv:'ارائیں بنوں ماحولیاتی تحفظ اور پائیداری کے لیے پرعزم ہے۔ ہم پودے لگانے، صاف پانی کے اقدامات اور ماحول دوست پروگراموں کو فروغ دیتے ہیں۔',
pageBodyGallery:'دنیا بھر کے شہروں میں ارائیں بنوں تقریبات، کمیونٹی اجتماعات اور سنگ میل سے تصاویر اور یادیں دیکھیں۔',
pageBodyDept:'ارائیں بنوں متعدد محکموں کے ذریعے کام کرتی ہے جن میں تعلیم، بہبود، نوجوانوں کے امور، خواتین کی بااختیاریت اور بین الاقوامی تعلقات شامل ہیں۔',
donateToAraainBannu:'ارائیں بنوں کو عطیہ دیں',
donSub:'آپ کا عطیہ براہ راست ارائیں برادری کی مدد کرتا ہے۔',
tabBank:'بینک ٹرانسفر',
tabEasypaisa:'Easypaisa',
tabJazzcash:'JazzCash',
tabInternational:'بین الاقوامی',
bankName:'بینک کا نام',
accountTitle:'اکاؤنٹ کا عنوان',
accountNo:'اکاؤنٹ نمبر',
branchCode:'برانچ کوڈ',
IBAN:'IBAN',
suggestedAmounts:'تجویز کردہ عطیہ:',
custom:'اپنی رقم',
bankNote:'منتقلی کے بعد رسید ای میل یا واٹس ایپ پر بھیجیں۔',
  donFormTitle:'اپنا عطیہ درج کریں',
  donFormSub:'رقم منتقل کرنے کے بعد اپنی تفصیلات درج کریں تاکہ ہم تصدیق کر سکیں۔',
  donorName:'پورا نام',
  donorPhone:'فون / واٹس ایپ',
  donorEmail:'ای میل (اختیاری)',
  donAmount:'عطیہ کی رقم',
  donMethod:'ادائیگی کا طریقہ',
  donTxID:'ٹرانزیکشن آئی ڈی / حوالہ نمبر',
  donTxIDPh:'مثال: TXN12345678',
  donNote:'اضافی نوٹ (اختیاری)',
  donNotePh:'ارائیں بنوں ٹیم کے لیے کوئی پیغام',
  donProof:'ادائیگی کا اسکرین شاٹ (اختیاری)',
  donSubmitBtn:'عطیہ ریکارڈ جمع کریں',
  donSubmitting:'جمع ہو رہا ہے…',
  donSuccess:'شکریہ! آپ کا عطیہ ریکارڈ موصول ہو گیا۔ ہم جلد تصدیق کر کے رابطہ کریں گے۔',
easypaisaNote:'Easypaisa ایپ ← پیسے بھیجیں ← موبائل اکاؤنٹ۔ منتقلی کے بعد اسکرین شاٹ بھیجیں۔',
jazzcashNote:'JazzCash ایپ ← پیسے بھیجیں ← موبائل پر۔ منتقلی کے بعد اسکرین شاٹ بھیجیں۔',
intNote:'بین الاقوامی ٹرانسفر کے لیے 3-5 کاروباری دن لگتے ہیں۔ حوالہ نمبر کے ساتھ ای میل کریں۔',
service:'سروس',
mobileNo:'موبائل نمبر',
memAppTitle:'رکنیت کی درخواست — ارائیں بنوں',
memAppSub:'ہمارے ساتھ شامل ہوں! ارائیں بنوں کے رکن بننے کے لیے نیچے فارم بھریں۔',
memInstrTitle:'فارم ہدایات',
memInstr1:'تمام ضروری خانوں میں درست اور مکمل معلومات فراہم کریں۔',
memInstr2:'آپ کا واٹس ایپ نمبر فعال ہونا چاہیے۔',
memInstr3:'شناختی کارڈ اور ای میل اختیاری ہیں لیکن درست تفصیلات تجویز کی جاتی ہیں۔',
memInstr4:'ہماری ٹیم جائزے کے بعد آپ سے رابطہ کرے گی۔',
memInstr5:'ادھوری معلومات رد کا سبب بن سکتی ہے۔',
memNote:'مل کر ترقی کریں — ارائیں بنوں',
memPersonal:'ذاتی معلومات',
memContact:'رابطہ اور رہائشی',
memProfessional:'پیشہ ورانہ معلومات',
memAddress:'پروفائل تصویر اور پتہ',
memTermsTitle:'شرائط و ضوابط',
memTerm1:'فراہم کردہ معلومات درست اور مکمل ہیں۔',
memTerm2:'ارائیں بنوں کسی بھی درخواست کو قبول یا رد کرنے کا حق رکھتی ہے۔',
memTerm3:'رکنیت سیاسی یا غیر قانونی مقاصد کے لیے استعمال نہیں ہوگی۔',
memConsent:'میں رکنیت کی شرائط سے متفق ہوں',
submitApp:'درخواست جمع کرائیں',
submitting:'بھیجا جا رہا ہے…',
appSuccess:'آپ کی درخواست کامیابی سے جمع ہو گئی! ہماری ٹیم جلد آپ سے رابطہ کرے گی۔',
msgSuccess:'پیغام کامیابی سے بھیج دیا گیا!',
sending:'بھیجا جا رہا ہے…',
fFullName:'پورا نام *',
fFatherName:'والد کا نام *',
fGender:'جنس *',
fMemberType:'رکنیت کی قسم *',
fCnic:'شناختی کارڈ نمبر',
fDob:'تاریخ پیدائش *',
fEmailF:'ای میل *',
fWhatsapp:'واٹس ایپ نمبر *',
fResidential:'رہائشی حیثیت *',
fAffiliated:'کسی تنظیم سے وابستہ؟ *',
fEducation:'تعلیمی قابلیت *',
fWork:'کام کی معلومات *',
fReason:'آپ ارائیں بنوں میں کیوں شامل ہونا چاہتے ہیں؟',
fPhoto:'پروفائل تصویر',
fStreet:'گلی کا پتہ *',
fCity:'شہر *',
fState:'صوبہ *',
fCountry:'ملک *',
selectOpt:'آپشن منتخب کریں',
gFemale:'خاتون',
gMale:'مرد',
gOther:'دیگر',
mExec:'ایگزیکٹو رکن',
mGeneral:'عام رکن',
mYouth:'نوجوان رکن',
mAssoc:'ایسوسی ایٹ رکن',
rResident:'مقیم پاکستانی',
rOverseas:'بیرون ملک پاکستانی',
yes:'ہاں',
no:'نہیں',
eMatric:'میٹرک',
eInter:'انٹرمیڈیٹ',
eGrad:'گریجویٹ',
ePG:'پوسٹ گریجویٹ',
eOther:'دیگر',
wStudent:'طالب علم',
wJob:'ملازم',
wGov:'سرکاری ملازم',
wBiz:'کاروباری',
wFree:'فری لانسر',
phFullName:'محمد علی ارائیں',
phFatherName:'محمد اکرم ارائیں',
phCnic:'XXXXX-XXXXXXX-X',
phWhatsapp:'+92XXXXXXXXXX',
phStreet:'مکان نمبر، گلی، علاقہ',
phCity:'بنوں',
phState:'خیبر پختونخوا',
phReason:'اپنی وجہ بیان کریں…',
cPakistan:'پاکستان',
cUSA:'امریکہ',
cUK:'برطانیہ',
cCanada:'کینیڈا',
cAustralia:'آسٹریلیا',
cUAE:'متحدہ عرب امارات',
cSaudi:'سعودی عرب',
cGermany:'جرمنی',
cFrance:'فرانس',
cNetherlands:'نیدرلینڈز',
cOther:'دیگر',  chairmanName:'طاہر میر',
  chairmanQuote:'اتحاد، بااختیاریت، اور ترقی — ارائیں بنوں کے تین ستون۔',

  contactAddressDefault:'بنوں، خیبرپختونخوا، پاکستان',
  contactHoursDefault:'پیر – جمعہ: صبح ۸ – شام ۶',
  contactEmailDefault:'admin@arainbannu.org',
  contactPhoneDefault:'+92-33-9192-9922',

langToggleLabel:'English',
};

// ── t(key, lang) — synchronous, no external dependencies ─────
// Returns the translation for `key` in the requested language.
// Falls back to the OTHER language only as absolute last resort
// (key truly missing from both) — never mixes languages silently.
export function t(key, lang) {
  const primary   = lang === 'ur' ? UR : EN;
  const secondary = lang === 'ur' ? EN : UR;
  if (primary[key]   !== undefined) return primary[key];
  if (secondary[key] !== undefined) return secondary[key];
  return key;  // bare key as last resort — never empty string
}
